### ISSUE TITLE
Include parents in function, decorator bodies

### ISSUE THREAD

**Issue by heaths** [happenslol/tree-sitter-typespec#3]
I customized the [highlights.scm](https://github.com/heaths/helix/blob/main/runtime/queries/typespec/highlights.scm) for my [Helix](https://github.com/helix-editor/helix) language support for TypeSpec and noticed that functions' and decorators' bodies are inconsistent with operations' body when it comes to including `()`. Compared to other language support in Helix, a gesture like `mif` (select inside function) or `mit` (select inside type) includes the parents/brackets but this does not seem achievable with functions and decorators because the parens are not part of the parameter list token.

I'm happy to submit a PR if you're open to having them included like they are for operations' body / param list.

[![asciicast](https://asciinema.org/a/VkGbOYkrgohBboBVDTnGQkiLB.svg)](https://asciinema.org/a/VkGbOYkrgohBboBVDTnGQkiLB)

**Comment by happenslol** [comment]
Sounds like this would improve consistency across different scopes, so yeah, I'm totally fine with you opening a PR for this. Thank you, and I'm happy to see this being used for other editors as well!

**Comment by heaths** [comment]
Thank you for starting the project! Will be nice seeing if VSCode ends up supporting tree-sitter and see your work included to make it better for TypeSpec.

**Comment by heaths** [comment]
Just to double check: was that pattern generated from <https://github.com/microsoft/typespec/blob/main/grammars/typespec.json> in some way that I should first upstream a change? Looking at <https://github.com/microsoft/typespec/blob/fa704283140eb278d4c66a6e350969bd418d0575/grammars/typespec.json#L844> vs. <https://github.com/microsoft/typespec/blob/fa704283140eb278d4c66a6e350969bd418d0575/grammars/typespec.json#L174>, I'm assuming this was a hand-written transpilation, right? A very good and thorough one, mind you! :smile:

Parsing through all the TM JSON therein is an eyesore unlike the tree-sitter grammar you've reconstructed here, so hoping you might remember off hand. Either way, I can work on a PR tonight or tomorrow night, but wanted to know if I should upstream a change to microsoft/typespec as well. I work in that team, though "adjacent".

**Comment by happenslol** [comment]
No, I started off trying to automatically transpile the grammar, but in the end it wasn't feasible and I ended up using [this grammar](https://github.com/microsoft/typespec/blob/fa704283140eb278d4c66a6e350969bd418d0575/packages/spec/src/spec.emu.html) I was pointed to by one of the devs in [this discussion](https://github.com/microsoft/typespec/discussions/3088).

I simply went through that grammar rule-by-rule and converted it, but I was also learning tree-sitter as I went, that's why there are small inconsistencies. The grammar for values is also not yet implemented, since I've been pretty busy, see #2.
